Repository tkdwls4453/ecommerce-msa-server, pull requests merged in 2025-02, with the labels that each got.

#49 chore : ci를 위한 product-ci.yml과 build.gradle 수정
  .github/workflows/product-ci.yml
  product-service/build.gradle
  product-service/src/main/java/com/msa/product/Calculator.java
  product-service/src/main/java/com/msa/product/ProductApplication.java
  product-service/src/test/java/com/msa/product/CalculatorTest.java
Labels: ⚙️ chore

#44 chore : product-service 모듈 init
  .github/workflows/product-ci.yml
  .idea/compiler.xml
  .idea/misc.xml
  product-service/build.gradle
  product-service/gradle/wrapper/gradle-wrapper.jar
  product-service/gradle/wrapper/gradle-wrapper.properties
  product-service/src/main/java/com/msa/product/Calculator.java
  product-service/src/main/java/com/msa/product/ProductApplication.java
  product-service/src/main/resources/application.properties
  product-service/src/test/java/com/msa/product/CalculatorTest.java
  product-service/src/test/java/com/msa/product/ProductApplicationTests.java
  settings.gradle
Labels: ⚙️ chore

#57 [Feat] 주문 접수 기능 개발
  common/src/main/java/com/msa/common/config/JacksonConfig.java
  common/src/main/java/com/msa/common/config/MoneyDeserializer.java
  common/src/main/java/com/msa/common/config/MoneySerializer.java
  common/src/main/java/com/msa/common/converter/IntToMoneyConverter.java
  common/src/main/java/com/msa/common/vo/Money.java
  order-service/src/main/java/com/msa/order/Calculator.java
  order-service/src/main/java/com/msa/order/OrderServiceApplication.java
  order-service/src/main/java/com/msa/order/adapter/in/web/OrderController.java
  order-service/src/main/java/com/msa/order/adapter/in/web/dto/CreateNewOrderRequest.java
  order-service/src/main/java/com/msa/order/adapter/in/web/dto/CreatedNewOrderResponse.java
  order-service/src/main/java/com/msa/order/adapter/out/FakeApplyCouponAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/FakeDecreaseStockAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderCommandAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderCommandJpaRepository.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderEntity.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderItemEntity.java
  order-service/src/main/java/com/msa/order/application/port/in/CreateNewOrderCommand.java
  order-service/src/main/java/com/msa/order/application/port/in/CreateNewOrderUseCase.java
  order-service/src/main/java/com/msa/order/application/port/out/ApplyCouponUseCase.java
  order-service/src/main/java/com/msa/order/application/port/out/DecreaseStockUseCase.java
  order-service/src/main/java/com/msa/order/application/port/out/OrderCreatePort.java
  order-service/src/main/java/com/msa/order/application/service/OrderService.java
  order-service/src/main/java/com/msa/order/domain/Order.java
  order-service/src/main/java/com/msa/order/domain/OrderStatus.java
  order-service/src/main/java/com/msa/order/domain/vo/AppliedCoupon.java
  order-service/src/main/java/com/msa/order/domain/vo/OrderItem.java
  order-service/src/main/java/com/msa/order/domain/vo/ShippingInfo.java
  order-service/src/main/java/com/msa/order/exception/InsufficientStockException.java
  order-service/src/main/java/com/msa/order/exception/InvalidCouponException.java
  order-service/src/main/java/com/msa/order/exception/InvalidCouponTypeException.java
  order-service/src/main/java/com/msa/order/exception/InvalidTotalPriceException.java
  order-service/src/main/java/com/msa/order/exception/NoOrderItemException.java
  order-service/src/main/java/com/msa/order/exception/OrderErrorCode.java
  order-service/src/test/java/com/msa/order/CalculatorTest.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderControllerTest.java
  order-service/src/test/java/com/msa/order/adapter/out/persistence/OrderCommandAdapterTest.java
  order-service/src/test/java/com/msa/order/application/service/OrderServiceTest.java
  order-service/src/test/java/com/msa/order/domain/OrderFixtures.java
  order-service/src/test/java/com/msa/order/domain/OrderTest.java
  user-service/src/test/java/com/msa/user/adapter/in/web/UserRegisterControllerTest.java
Labels: 🚀 feat

#60 [Chore] 결제 서비스 초기화 및 CI 설정
  .github/workflows/payment-ci.yml
  build.gradle
  docker-compose.yml
  payment-service/build.gradle
  payment-service/src/main/java/com/msa/payment/PaymentServiceApplication.java
  settings.gradle
  src/main/java/com/commerce/ecommercemsaserver/EcommerceMsaServerApplication.java
  src/main/java/com/commerce/ecommercemsaserver/test/TestController.java
  src/main/java/com/commerce/ecommercemsaserver/test/TestRequest.java
  src/main/java/com/commerce/ecommercemsaserver/test/exception/Test1Exception.java
  src/main/java/com/commerce/ecommercemsaserver/test/exception/Test2Exception.java
  src/main/java/com/commerce/ecommercemsaserver/test/exception/TestErrorCode.java
  src/main/resources/application.properties
  src/test/java/com/commerce/ecommercemsaserver/EcommerceMsaServerApplicationTests.java
Labels: ⚙️ chore

#63 [Feat] 결제 관련 기능 개발
  common/src/main/java/com/msa/common/config/JacksonConfig.java
  common/src/main/java/com/msa/common/config/MoneyDeserializer.java
  common/src/main/java/com/msa/common/response/ApiResponse.java
  payment-service/build.gradle
  payment-service/src/main/java/com/msa/payment/PaymentServiceApplication.java
  payment-service/src/main/java/com/msa/payment/adapter/in/web/PaymentController.java
  payment-service/src/main/java/com/msa/payment/adapter/in/web/dto/CreatePaymentRequest.java
  payment-service/src/main/java/com/msa/payment/adapter/in/web/dto/PaymentResponse.java
  payment-service/src/main/java/com/msa/payment/adapter/in/web/dto/VerifyPaymentRequest.java
  payment-service/src/main/java/com/msa/payment/adapter/out/FakeOrderAdapter.java
  payment-service/src/main/java/com/msa/payment/adapter/out/TossPaymentAdapter.java
  payment-service/src/main/java/com/msa/payment/adapter/out/feign/TossPaymentClient.java
  payment-service/src/main/java/com/msa/payment/adapter/out/feign/TossPaymentConfirmRequest.java
  payment-service/src/main/java/com/msa/payment/adapter/out/persistence/PaymentCommandAdapter.java
  payment-service/src/main/java/com/msa/payment/adapter/out/persistence/PaymentCommandJpaRepository.java
  payment-service/src/main/java/com/msa/payment/adapter/out/persistence/PaymentEntity.java
  payment-service/src/main/java/com/msa/payment/adapter/out/persistence/PaymentQueryAdapter.java
  payment-service/src/main/java/com/msa/payment/adapter/out/persistence/PaymentQueryJpaRepository.java
  payment-service/src/main/java/com/msa/payment/application/port/in/PaymentCommandUseCase.java
  payment-service/src/main/java/com/msa/payment/application/port/in/dto/CreatePaymentCommand.java
  payment-service/src/main/java/com/msa/payment/application/port/in/dto/VerifyPaymentCommand.java
  payment-service/src/main/java/com/msa/payment/application/port/out/ExternalPaymentPort.java
  payment-service/src/main/java/com/msa/payment/application/port/out/OrderCommandPort.java
  payment-service/src/main/java/com/msa/payment/application/port/out/OrderQueryPort.java
  payment-service/src/main/java/com/msa/payment/application/port/out/PaymentCommandPort.java
  payment-service/src/main/java/com/msa/payment/application/port/out/PaymentQueryPort.java
  payment-service/src/main/java/com/msa/payment/application/port/out/dto/ExternalPaymentResponse.java
  payment-service/src/main/java/com/msa/payment/application/port/out/dto/SimpleOrderResponse.java
  payment-service/src/main/java/com/msa/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/msa/payment/config/TossPaymentErrorDecoder.java
  payment-service/src/main/java/com/msa/payment/config/TossPaymentFeignConfig.java
  payment-service/src/main/java/com/msa/payment/domain/Payment.java
  payment-service/src/main/java/com/msa/payment/domain/PaymentStatus.java
  payment-service/src/main/java/com/msa/payment/exception/ExternalPaymentErrorException.java
  payment-service/src/main/java/com/msa/payment/exception/ExternalPaymentExceptionHandler.java
  payment-service/src/main/java/com/msa/payment/exception/OrderPermissionDeniedException.java
  payment-service/src/main/java/com/msa/payment/exception/PaymentErrorCode.java
  payment-service/src/main/java/com/msa/payment/exception/PaymentNotFoundException.java
  payment-service/src/main/java/com/msa/payment/exception/PaymentOrderInvalidException.java
  payment-service/src/main/java/com/msa/payment/exception/PriceMismatchException.java
  payment-service/src/main/resources/application.yml
  payment-service/src/test/java/com/msa/payment/adapter/in/web/PaymentControllerTest.java
  payment-service/src/test/java/com/msa/payment/adapter/out/TossPaymentAdapterTest.java
  payment-service/src/test/java/com/msa/payment/adapter/out/persistence/PaymentCommandAdapterTest.java
  payment-service/src/test/java/com/msa/payment/adapter/out/persistence/PaymentQueryAdapterTest.java
  payment-service/src/test/java/com/msa/payment/application/service/PaymentServiceTest.java
  payment-service/src/test/java/com/msa/payment/domain/OrderFixtures.java
  payment-service/src/test/java/com/msa/payment/domain/PaymentFixtures.java
  payment-service/src/test/java/com/msa/payment/domain/PaymentTest.java
Labels: 🚀 feat

#66 [Feat] MSA 설정
  docker-compose.yml
  eureka-server/src/main/java/com/msa/eureka/EurekaServerApplication.java
  eureka-server/src/main/java/com/msa/eureka/security/SecurityConfig.java
  eureka-server/src/main/resources/application.yml
  gateway-server/src/main/java/com/msa/gateway/GatewayServerApplication.java
  gateway-server/src/main/java/com/msa/gateway/config/CustomRoute.java
  gateway-server/src/main/resources/application.yml
  order-service/build.gradle
  order-service/src/main/java/com/msa/order/OrderServiceApplication.java
  order-service/src/main/resources/application.yml
  settings.gradle
  user-service/build.gradle
  user-service/src/main/resources/application.yml
Labels: 🚀 feat

#74 [Feat] 유저 인증 처리
  docker-compose.yml
  gateway-server/build.gradle
  gateway-server/src/main/java/com/msa/gateway/GatewayServerApplication.java
  gateway-server/src/main/java/com/msa/gateway/config/CustomRoute.java
  gateway-server/src/main/java/com/msa/gateway/config/WhitelistUrls.java
  gateway-server/src/main/java/com/msa/gateway/filter/AuthorizationHeaderFilter.java
  payment-service/build.gradle
  payment-service/src/main/resources/application.yml
Labels: 🚀 feat

#76 [Refactor] jwt 모듈 분리
  .idea/compiler.xml
  .idea/misc.xml
  common/src/main/resources/application.yml
  docker-compose.yml
  gateway-server/build.gradle
  gateway-server/src/main/java/com/msa/gateway/GatewayServerApplication.java
  gateway-server/src/main/java/com/msa/gateway/filter/AuthorizationHeaderFilter.java
  jwt/build.gradle
  jwt/src/main/java/com/msa/jwt/JwtUtil.java
  settings.gradle
  user-service/build.gradle
  user-service/src/main/java/com/msa/user/UserServiceApplication.java
  user-service/src/main/java/com/msa/user/adapter/in/web/filter/AuthenticationFilter.java
  user-service/src/main/java/com/msa/user/config/SecurityConfig.java
  user-service/src/test/java/com/msa/user/adapter/in/web/filter/AuthenticationFilterTest.java
Labels: ⚒️ refactor

#77 [Feat] 간단 주문 정보 조회 기능 개발
  .idea/compiler.xml
  .idea/misc.xml
  common/src/main/resources/application.yml
  docker-compose.yml
  gateway-server/build.gradle
  gateway-server/src/main/java/com/msa/gateway/GatewayServerApplication.java
  gateway-server/src/main/java/com/msa/gateway/config/CustomRoute.java
  gateway-server/src/main/java/com/msa/gateway/config/WhitelistUrls.java
  gateway-server/src/main/java/com/msa/gateway/filter/AuthorizationHeaderFilter.java
  jwt/build.gradle
  jwt/src/main/java/com/msa/jwt/JwtUtil.java
  order-service/src/main/java/com/msa/order/OrderServiceApplication.java
  order-service/src/main/java/com/msa/order/adapter/in/web/OrderController.java
  order-service/src/main/java/com/msa/order/adapter/in/web/OrderInternalController.java
  order-service/src/main/java/com/msa/order/adapter/in/web/dto/CreatedNewOrderResponse.java
  order-service/src/main/java/com/msa/order/adapter/in/web/dto/SimpleOrderResponse.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderQueryAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderQueryJpaRepository.java
  order-service/src/main/java/com/msa/order/application/port/in/OrderQueryUseCase.java
  order-service/src/main/java/com/msa/order/application/port/out/OrderQueryPort.java
  order-service/src/main/java/com/msa/order/application/service/OrderCommandService.java
  order-service/src/main/java/com/msa/order/application/service/OrderQueryService.java
  order-service/src/main/java/com/msa/order/exception/NotFoundOrderException.java
  order-service/src/main/java/com/msa/order/exception/OrderErrorCode.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderControllerTest.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderInternalControllerTest.java
  order-service/src/test/java/com/msa/order/adapter/out/persistence/OrderQueryAdapterTest.java
  order-service/src/test/java/com/msa/order/application/service/OrderQueryServiceTest.java
  order-service/src/test/java/com/msa/order/application/service/OrderServiceTest.java
  payment-service/build.gradle
  payment-service/src/main/resources/application.yml
  settings.gradle
  user-service/build.gradle
  user-service/src/main/java/com/msa/user/UserServiceApplication.java
  user-service/src/main/java/com/msa/user/adapter/in/web/filter/AuthenticationFilter.java
  user-service/src/main/java/com/msa/user/config/SecurityConfig.java
  user-service/src/test/java/com/msa/user/adapter/in/web/filter/AuthenticationFilterTest.java
Labels: 🚀 feat

#82 [Feat] 주문 준비 기능 개발
  order-service/src/main/java/com/msa/order/adapter/in/web/OrderInternalController.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderCommandAdapter.java
  order-service/src/main/java/com/msa/order/application/port/in/PrepareOrderUseCase.java
  order-service/src/main/java/com/msa/order/application/port/out/OrderCommandPort.java
  order-service/src/main/java/com/msa/order/application/service/OrderCommandService.java
  order-service/src/main/java/com/msa/order/domain/Order.java
  order-service/src/main/java/com/msa/order/exception/InvalidOrderStatusException.java
  order-service/src/main/java/com/msa/order/exception/OrderErrorCode.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderControllerTest.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderInternalControllerTest.java
  order-service/src/test/java/com/msa/order/application/service/OrderCommandServiceTest.java
  order-service/src/test/java/com/msa/order/domain/OrderTest.java
Labels: 🚀 feat

#84 [Feat] 주문 관련 변경 develop 브랜치에 반영
  gateway-server/src/main/java/com/msa/gateway/config/CustomRoute.java
  order-service/src/main/java/com/msa/order/OrderServiceApplication.java
  order-service/src/main/java/com/msa/order/adapter/in/web/OrderController.java
  order-service/src/main/java/com/msa/order/adapter/in/web/OrderInternalController.java
  order-service/src/main/java/com/msa/order/adapter/in/web/dto/CreatedNewOrderResponse.java
  order-service/src/main/java/com/msa/order/adapter/in/web/dto/SimpleOrderResponse.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderCommandAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderQueryAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/persistence/OrderQueryJpaRepository.java
  order-service/src/main/java/com/msa/order/application/port/in/OrderQueryUseCase.java
  order-service/src/main/java/com/msa/order/application/port/in/PrepareOrderUseCase.java
  order-service/src/main/java/com/msa/order/application/port/out/OrderCommandPort.java
  order-service/src/main/java/com/msa/order/application/port/out/OrderQueryPort.java
  order-service/src/main/java/com/msa/order/application/service/OrderCommandService.java
  order-service/src/main/java/com/msa/order/application/service/OrderQueryService.java
  order-service/src/main/java/com/msa/order/domain/Order.java
  order-service/src/main/java/com/msa/order/exception/InvalidOrderStatusException.java
  order-service/src/main/java/com/msa/order/exception/NotFoundOrderException.java
  order-service/src/main/java/com/msa/order/exception/OrderErrorCode.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderControllerTest.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderInternalControllerTest.java
  order-service/src/test/java/com/msa/order/adapter/out/persistence/OrderQueryAdapterTest.java
  order-service/src/test/java/com/msa/order/application/service/OrderCommandServiceTest.java
  order-service/src/test/java/com/msa/order/application/service/OrderQueryServiceTest.java
  order-service/src/test/java/com/msa/order/domain/OrderTest.java
Labels: 🚀 feat

#86 [Feat] 주문 서비스 연동 부분 deveop 브랜치에 반영
  common/src/main/java/com/msa/common/exception/FeignClientException.java
  common/src/main/java/com/msa/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/msa/common/response/ApiResponse.java
  gateway-server/src/main/java/com/msa/gateway/filter/AuthorizationHeaderFilter.java
  payment-service/src/main/java/com/msa/payment/PaymentServiceApplication.java
  payment-service/src/main/java/com/msa/payment/adapter/in/web/PaymentController.java
  payment-service/src/main/java/com/msa/payment/adapter/out/FakeOrderAdapter.java
  payment-service/src/main/java/com/msa/payment/adapter/out/OrderFeignAdapter.java
  payment-service/src/main/java/com/msa/payment/adapter/out/feign/OrderFeignClient.java
  payment-service/src/main/java/com/msa/payment/application/port/out/dto/SimpleOrderResponse.java
  payment-service/src/main/java/com/msa/payment/application/service/PaymentService.java
  payment-service/src/main/java/com/msa/payment/domain/Payment.java
  payment-service/src/main/java/com/msa/payment/exception/PaymentErrorCode.java
  payment-service/src/test/java/com/msa/payment/adapter/in/web/PaymentControllerTest.java
  payment-service/src/test/java/com/msa/payment/adapter/out/OrderFeignAdapterTest.java
  payment-service/src/test/java/com/msa/payment/domain/OrderFixtures.java
Labels: 🚀 feat

#88 [Feat] 재고 감소/복구 기능 개발
  product-service/src/main/java/com/msa/product/adapter/in/web/ShoesController.java
  product-service/src/main/java/com/msa/product/adapter/in/web/ShoesInternalController.java
  product-service/src/main/java/com/msa/product/adapter/in/web/dto/DecreaseStockRequest.java
  product-service/src/main/java/com/msa/product/adapter/in/web/dto/RollbackStockRequest.java
  product-service/src/main/java/com/msa/product/adapter/out/persistence/ShoesCommandAdapter.java
  product-service/src/main/java/com/msa/product/adapter/out/persistence/ShoesCommandJpaRepository.java
  product-service/src/main/java/com/msa/product/adapter/out/persistence/ShoesEntity.java
  product-service/src/main/java/com/msa/product/adapter/out/persistence/ShoesQueryAdapter.java
  product-service/src/main/java/com/msa/product/adapter/out/persistence/ShoesQueryJpaRepository.java
  product-service/src/main/java/com/msa/product/application/port/in/DecreaseStockCommand.java
  product-service/src/main/java/com/msa/product/application/port/in/OrderItem.java
  product-service/src/main/java/com/msa/product/application/port/in/ProductStockUseCase.java
  product-service/src/main/java/com/msa/product/application/port/in/RollbackStockCommand.java
  product-service/src/main/java/com/msa/product/application/port/out/ShoesQueryPort.java
  product-service/src/main/java/com/msa/product/application/port/out/ShoesStockManagePort.java
  product-service/src/main/java/com/msa/product/application/service/ShoesStockManageService.java
  product-service/src/main/java/com/msa/product/domain/Shoes.java
  product-service/src/main/java/com/msa/product/domain/ShoesFactory.java
  product-service/src/main/java/com/msa/product/domain/vo/Quantity.java
  product-service/src/main/java/com/msa/product/exception/InsufficientStockException.java
  product-service/src/main/java/com/msa/product/exception/NotFoundShoesException.java
  product-service/src/main/java/com/msa/product/exception/ProductErrorCode.java
  product-service/src/test/java/com/msa/product/ProductApplicationTests.java
  product-service/src/test/java/com/msa/product/adapter/in/web/ShoesInternalControllerTest.java
  product-service/src/test/java/com/msa/product/adapter/out/persistence/ShoesCommandAdapterTest.java
  product-service/src/test/java/com/msa/product/adapter/out/persistence/ShoesCommandJpaRepositoryTest.java
  product-service/src/test/java/com/msa/product/adapter/out/persistence/ShoesQueryAdapterTest.java
  product-service/src/test/java/com/msa/product/adapter/out/persistence/ShoesQueryJpaRepositoryTest.java
  product-service/src/test/java/com/msa/product/application/service/ShoesStockManageServiceTest.java
  product-service/src/test/java/com/msa/product/domain/ProductFixtures.java
  product-service/src/test/java/com/msa/product/domain/ShoesTest.java
  product-service/src/test/java/com/msa/product/integration/StockIntegrationTest.java
  product-service/src/test/resources/application.yml
Labels: 🚀 feat

#50 chore: 쿠폰 프로젝트 초기화
  .github/workflows/coupon-ci.yml
  common/src/test/java/com/msa/common/utils/JwtUtilTest.java
  coupon-service/build.gradle
  coupon-service/gradle/wrapper/gradle-wrapper.jar
  coupon-service/gradle/wrapper/gradle-wrapper.properties
  coupon-service/src/main/java/com/msa/couponservice/Calculator.java
  coupon-service/src/main/java/com/msa/couponservice/CouponServiceApplication.java
  coupon-service/src/main/resources/application.properties
  coupon-service/src/test/java/com/msa/couponservice/CalculatorTest.java
  coupon-service/src/test/java/com/msa/couponservice/CouponServiceApplicationTests.java
  eureka-server/build.gradle
  settings.gradle
Labels: ⚙️ chore

#95 [Feat] 재고 관리에 레디스 적용
  .github/workflows/coupon-ci.yml
  common/src/test/java/com/msa/common/utils/JwtUtilTest.java
  coupon-service/build.gradle
  coupon-service/gradle/wrapper/gradle-wrapper.jar
  coupon-service/gradle/wrapper/gradle-wrapper.properties
  coupon-service/src/main/java/com/msa/couponservice/Calculator.java
  coupon-service/src/main/java/com/msa/couponservice/CouponServiceApplication.java
  coupon-service/src/main/resources/application.properties
  coupon-service/src/test/java/com/msa/couponservice/CalculatorTest.java
  coupon-service/src/test/java/com/msa/couponservice/CouponServiceApplicationTests.java
  docker-compose.yml
  eureka-server/build.gradle
  order-service/build.gradle
  order-service/src/main/java/com/msa/order/OrderServiceApplication.java
  order-service/src/main/java/com/msa/order/adapter/in/web/OrderController.java
  order-service/src/main/java/com/msa/order/adapter/out/FakeDecreaseStockAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/ProductFeignAdapter.java
  order-service/src/main/java/com/msa/order/adapter/out/feign/DecreaseStockRequest.java
  order-service/src/main/java/com/msa/order/adapter/out/feign/ProductFeignClient.java
  order-service/src/main/java/com/msa/order/adapter/out/feign/RollbackStockRequest.java
  order-service/src/main/java/com/msa/order/application/port/out/ProductStockManagePort.java
  order-service/src/main/java/com/msa/order/application/service/OrderCommandService.java
  order-service/src/test/java/com/msa/order/adapter/in/web/OrderControllerTest.java
  order-service/src/test/java/com/msa/order/application/service/OrderCommandServiceTest.java
  product-service/build.gradle
  product-service/src/main/java/com/msa/product/adapter/in/web/ShoesInternalController.java
  product-service/src/main/java/com/msa/product/adapter/out/persistence/ShoesQueryAdapter.java
  product-service/src/main/java/com/msa/product/adapter/out/redis/RedisStockManageAdapter.java
  product-service/src/main/java/com/msa/product/application/port/in/ProductRedisStockUseCase.java
  product-service/src/main/java/com/msa/product/application/port/out/ShoesQueryPort.java
  product-service/src/main/java/com/msa/product/application/port/out/ShoesRedisStockManagePort.java
  product-service/src/main/java/com/msa/product/application/service/ShoesRedisStockManageService.java
  product-service/src/main/java/com/msa/product/config/LuaScriptConfig.java
  product-service/src/main/java/com/msa/product/config/RedisConfig.java
  product-service/src/main/resources/application.yml
  product-service/src/main/resources/scripts/decreaseStock.lua
  product-service/src/main/resources/scripts/increaseStock.lua
  product-service/src/test/java/com/msa/product/adapter/in/web/ShoesInternalControllerTest.java
  product-service/src/test/java/com/msa/product/adapter/out/persistence/ShoesCommandJpaRepositoryTest.java
  product-service/src/test/java/com/msa/product/adapter/out/persistence/ShoesQueryJpaRepositoryTest.java
  product-service/src/test/java/com/msa/product/integration/StockIntegrationTest.java
  product-service/src/test/resources/application.yml
  settings.gradle
Labels: 🚀 feat
