Repository tkdwls4453/ecommerce-msa-server, pull requests merged in 2025-01, with the labels that each got.

#13 feat: 공통 모듈 패키지 작성
  .idea/.gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  common/build.gradle
  common/src/main/resources/application.yml
  settings.gradle
Labels: 🚀 feat

#14 docs : PR 템플릿 파일 추가
  pull_request_template.md
Labels: 📄 doc s

#17 feat : JsonValueRedisTemplate 부분 구현
  .github/pull_request_template.md
  .idea/compiler.xml
  .idea/misc.xml
  common/build.gradle
  common/src/main/java/com/msa/common/redis/JsonValueRedisTemplate.java
Labels: 🚀 feat

#24 Feature/#16 global exception
  build.gradle
  common/src/main/java/com/msa/common/exception/CustomException.java
  common/src/main/java/com/msa/common/exception/CustomExceptionHandler.java
  common/src/main/java/com/msa/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/msa/common/response/ApiResponse.java
  common/src/main/java/com/msa/common/response/GlobalStatusCode.java
  common/src/main/java/com/msa/common/response/ResponseStatus.java
  common/src/main/java/com/msa/common/response/StatusCode.java
  src/main/java/com/commerce/ecommercemsaserver/EcommerceMsaServerApplication.java
  src/main/java/com/commerce/ecommercemsaserver/test/TestController.java
  src/main/java/com/commerce/ecommercemsaserver/test/TestRequest.java
  src/main/java/com/commerce/ecommercemsaserver/test/exception/Test1Exception.java
  src/main/java/com/commerce/ecommercemsaserver/test/exception/Test2Exception.java
  src/main/java/com/commerce/ecommercemsaserver/test/exception/TestErrorCode.java
Labels: 🚀 feat

#26 feat : RedisHashTemplate 구현
  common/src/main/java/com/msa/common/redis/HashRedisTemplate.java
Labels: 🚀 feat

#29 chore: ci 설정 파일 작성
  .github/workflows/user-ci.yml
  user-service/build.gradle
Labels: ⚙️ chore

#31 jacoco 버전 문제 해결
  .github/workflows/user-ci.yml
  user-service/build.gradle
Labels: ⚙️ chore

#32 feat : JsonValueRedisTemplate 추가 기능 구현 #12
  common/src/main/java/com/msa/common/redis/JsonValueRedisTemplate.java
Labels: 🚀 feat, ⚒️ refactor

#35 feat : RedisParsingException 추가 및 핸들링
  common/src/main/java/com/msa/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/msa/common/exception/RedisParsingException.java
  common/src/main/java/com/msa/common/redis/JsonValueRedisTemplate.java
  common/src/main/java/com/msa/common/response/GlobalStatusCode.java
Labels: 🚀 feat

#41 [Test] CI 테스트 진행
  order-service/build.gradle
  order-service/src/main/java/com/msa/order/Calculator.java
  order-service/src/main/java/com/msa/order/OrderServiceApplication.java
  order-service/src/test/java/com/msa/order/CalculatorTest.java
Labels: ⚙️ chore

#48 fix: 테스트 제외안되는 문제 해결
  order-service/build.gradle
  order-service/src/main/java/com/msa/order/Calculator.java
  order-service/src/test/java/com/msa/order/CalculatorTest.java
Labels: 🐛 fix
